# Generated by Django 5.1.1 on 2024-11-24 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_document_options_remove_document_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='grade',
            field=models.ForeignKey(db_column='gradeid', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='instructor.grade'),
            preserve_default=False,
        ),
    ]
