# Generated by Django 5.1.1 on 2024-11-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_remove_document_grade_document_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('clusterid', models.AutoField(primary_key=True, serialize=False)),
                ('clustername', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clusters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('standardid', models.AutoField(primary_key=True, serialize=False)),
                ('standardcode', models.CharField(max_length=50)),
                ('standarddescription', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'standards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('example_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'examples',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='DocumentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(help_text='NLI confidence score for this document-standard relationship')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, to='instructor.document')),
                ('standard', models.ForeignKey(db_column='standard_id', on_delete=django.db.models.deletion.CASCADE, to='instructor.standards')),
            ],
            options={
                'db_table': 'document_standards',
                'indexes': [models.Index(fields=['document', 'standard'], name='document_st_documen_50cae4_idx'), models.Index(fields=['confidence_score'], name='document_st_confide_64f97a_idx')],
                'unique_together': {('document', 'standard')},
            },
        ),
        migrations.CreateModel(
            name='ExampleStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.example')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.standards')),
            ],
            options={
                'db_table': 'example_standards',
                'unique_together': {('example', 'standard')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.exercise')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.standards')),
            ],
            options={
                'db_table': 'exercise_standards',
                'unique_together': {('exercise', 'standard')},
            },
        ),
    ]
