# docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules

    depends_on:
      - backend
    
    # command: ["npm", "run", "start", "--", "--host", "0.0.0.0"]
    

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  
  db:
    image: postgres:latest
    ports:  # Move the ports key here, not inside the environment block
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:  # Add this to correctly load your environment variables
      - ./backend/.env


volumes:
  static_volume:
  db_data:
